### ISSUE TITLE
Clean up Header and Footer

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#10]
https://trello.com/c/EKL2Lhfb/56-clean-up-header-and-footer

- [x] FE: Add Board of Directors
- [x] FE: Make fonts work properly
- [x] FE: Clean up footer links
- [x] FE: Link to social media on header (see below)
- [x] FE: Link to social media on footer (see below)
- [x] FE: footer->Contact us: emailto:info@internationalmentorship.org

- [x] FE: Update style of header and footer

- [x] FE: Header: Make about us a dropdown menu with options "Who we are" and "Leadership"

IG: https://www.instagram.com/internationalstudentmp/
FB:https://www.facebook.com/internationalstudentmp

**Comment by richyen** [comment]
- [ ] FE: Clean up header links (Make it match Figma)
- [ ] FE: Add Board of Directors
- [ ] FE: Make fonts work properly
- [ ] FE: Clean up footer links
- [ ] FE: Link to social media (see comment)

**Comment by JonSEng** [comment]
Thanks @richyen I moved it into the main issue card so it shows up as subtasks.

<img width="352" alt="Screenshot 2020-06-06 23 07 31" src="https://user-images.githubusercontent.com/1644269/83961692-8162bf00-a84a-11ea-8f43-6fb58d0a22aa.png">

**Comment by douglaschan32167** [comment]
Please note that in the newer mock-ups, the footer is now blue.

**Comment by iksoosong** [comment]
@dougchansolute are we only having 2 languages now, Chinese and English? That's what the new mocks show

**Comment by douglaschan32167** [comment]
@iksoosong Yeah we're only supporting Chinese and English for the V1, and we're only going to translate the home page. for now. We'll add more languages later.
The chinese there already is from google translate. We're  going to replace it once we get an actual translation.

Also, I need to get rid of that dougchansolute account. That was my old work account which I accidentally pushed with once. The github account I use is @douglaschan32167

**Comment by iksoosong** [comment]
fyi, started working on it, anyone else feel free to pick it up since i haven't had a chance to work on this

**Comment by iksoosong** [comment]
Broke it down into smaller tasks.
