### ISSUE TITLE
Update About us page to match with figma design

### ISSUE THREAD

**Issue by misunchoi** [International-Mentorship-ISMP/ismp#109]
https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=492%3A137

- [ ] Finalized list of schools
- [ ] Ok to use images for schools

**Comment by lillyglin** [comment]
Final list of campuses can be found here: https://3.basecamp.com/4474129/buckets/16925967/google_documents/2757687127 (under tab "Campuses")

**Comment by lillyglin** [comment]
Duplicate #130. Closing out.
