### ISSUE TITLE
Integration of Google Tag Manager for Analytics

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#12]
Integrate Google Analytics into our website.

- [ ] Use this for dataLayer Push specification (call Dustin Chen if need help)
docs.google.com/document/d/1LD1-3i5FaOoU5nVvFJQFkGi4DIn236zMG9gbg7A39w8/edit

**Comment by richyen** [comment]
Use this for dataLayer Push specification (call Dustin Chen if need help)
https://docs.google.com/document/d/1LD1-3i5FaOoU5nVvFJQFkGi4DIn236zMG9gbg7A39w8/edit

**Comment by JonSEng** [comment]
Hi @lillyglin is this a V1 thing?

**Comment by douglaschan32167** [comment]
Do you want it to be? It was one of the things that I cut when we were trying to figure out the bare minimum for the June 15 deadline @JonSEng . I was going to bring it back in only if we finish everything else for the MVP. Unless you or @iksoosong wants to take it.

**Comment by JonSEng** [comment]
> Do you want it to be? It was one of the things that I cut when we were trying to figure out the bare minimum for the June 15 deadline @JonSEng . I was going to bring it back in only if we finish everything else for the MVP. Unless you or @iksoosong wants to take it.

No I don't :) I think V1 is already too tight given our deadlines. I just didn't know you already talked to folks and cut it out.

**Comment by lillyglin** [comment]
@JonSEng @douglaschan32167 I will be devil's advocate and say that it would be good to get this in earlier than later for SEO/ranking purposes. We'll have to let Dustin know that this is lower in priority (like a "we'll get to it when other things are done")

**Comment by JonSEng** [comment]
Okay - we'll have it not explicitly in V1 but in V1.1 but on the Board so we can pick it up soon right after the core V1 stuff. That sound alright @lillyglin ?

**Comment by lillyglin** [comment]
@JonSEng Sounds gouda. 🧀

**Comment by iksoosong** [comment]
Fyi, if someone else ends up picking this up, this actually makes use of [Google Tag Manager](https://marketingplatform.google.com/about/tag-manager/), not Google Analytics.

**Comment by douglaschan32167** [comment]
@iksoosong you're not working on this anymore right? I'm going to take a crack at it.

**Comment by iksoosong** [comment]
@douglaschan32167 go for it. I sent over what I have so far (not much)
https://github.com/International-Mentorship-ISMP/ismp/pull/286
I've only been able to take a look at it for a little at a time as I'm juggling different things, so if you can get this off the ground, that sgtm.
