### ISSUE TITLE
Application Form handle backend failure

### ISSUE THREAD

**Issue by kailanjian** [International-Mentorship-ISMP/ismp#123]
In the case that posting the form fails, there is currently no logic to handle what the frontend should display. It just remains on the last page of the form and throws a console error.

- [x] Investigate any ways to send invalid data to backend with passing frontend validations
- [x] Display a toast message on failure, with a hopefully helpful message
- [x] Invalidate broken fields if necessary (or just improve frontend validations...?)
- [x] Handle the case of network failure, or timeout gracefully (tell the user to try again, don't lose data if possible)

**Comment by JonSEng** [comment]
This seems to be important for V1. Adding it in there.
cc @lillyglin

**Comment by JonSEng** [comment]
This seems to be important for V1. Adding it in there.
Thanks for filing this @kailanjian 
cc @lillyglin

**Comment by JonSEng** [comment]
This seems to be important for V1. Adding it in there.
Thanks for filing this @kailanjian 
cc @lillyglin

**Comment by lillyglin** [comment]
@kailanjian How much time would it take to put these in place? cc @JonSEng

**Comment by kailanjian** [comment]
The toast message will probably be the hardest part, and I estimate maybe 1 or 2 hours at most. After that I just need to make sure the frontend validations match the backend (or are stricter) and this shouldn't be a problem anymore

**Comment by JonSEng** [comment]
> The toast message will probably be the hardest part, and I estimate maybe 1 or 2 hours at most. After that I just need to make sure the frontend validations match the backend (or are stricter) and this shouldn't be a problem anymore

I defer to @kailanjian on this.

**Comment by lillyglin** [comment]
@kailanjian Ok, let's go for it after you're done with application form.
