### ISSUE TITLE
Home page testimonial sliders

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#128]
- [x] Initial layout with dummy data
- [x] Populate with meaningful testimonials
- [x] Needs design for new information (name, major, school, year, photo)

Testimonials, student info, photos found here: https://3.basecamp.com/4474129/buckets/16925967/documents/2774301037

just missing one photo.

**Comment by douglaschan32167** [comment]
initial layout is in review. Once that's done, move this to blocked.

**Comment by lillyglin** [comment]
@jessewoo @albertjke We need to adjust this based on new information we're highlighting:
Name, major, school, year, photo, and testimonial

**Comment by lillyglin** [comment]
Moving this from blocked to in progress. @samdkuo

**Comment by JonSEng** [comment]
Hi @samdkuo just wondering is there a PR we can follow?
@lillyglin and I were trying to assess our status across the board.

**Comment by samdkuo** [comment]
Hi @JonSEng i have a pull request waiting for review right now, is that what you mean?

**Comment by douglaschan32167** [comment]
I made another ticket for the missing photo, so I'm closing this ticket.
