### ISSUE TITLE
Blog Article Page

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#13]
Figma Link:
https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=303%3A469

- [x] BE: Implement REST API Call
- [x] FE: Retrieve article via REST API
- [x] FE: Build layout
- [x] FE: Add apply-now button/banner
- [x] FE: Add Recommended articles at the bottom (Corea)
- [ ] BE: Implement Relevant Blogposts (4 most current blogposts; show 3, use 4th if current blogpost is in top-3)

**Comment by richyen** [comment]
- [ ] BE: Implement REST API Call
- [ ] FE: Retrieve article via REST API
- [ ] FE: Build layout
- [ ] FE: Add apply-now button/banner
- [ ] FE: Add Recommended articles at the bottom (Corea)
- [ ] BE: Implement Relevant Blogposts (4 most current blogposts; show 3, use 4th if current blogpost is in top-3)

**Comment by richyen** [comment]
@vickyadebona working on renderblog css

**Comment by vickyadebona** [comment]
@douglaschan32167 Just wondering, is the blogpost `media_url` field supposed to be the header image/video?

**Comment by douglaschan32167** [comment]
@vickyadebona Yes, `media_url` should be what goes in the header. 
Re: tags and topics, I'll see if I can include those in the blogpost that gets passed with the blogpostcontent. I think from a data association perspective it makes sense that a blogpost is a particular topic regardless of what language it's in, but I'll look into including them in the json object.

**Comment by douglaschan32167** [comment]
Once https://github.com/International-Mentorship-ISMP/ismp/pull/78 gets approved you will be able to see a fields called tag_set and topic_set within blogpost. It's a little bit cumbersome but it should give you the information you need.

**Comment by douglaschan32167** [comment]
@vickyadebona ^

**Comment by vickyadebona** [comment]
@douglaschan32167 thanks, that will be helpful!

**Comment by douglaschan32167** [comment]
#78 got merged so you should be able to see the topic_set now.

**Comment by douglaschan32167** [comment]
splitting this out into tickets #135 #136 #138 #141 #142
