### ISSUE TITLE
Subpage: Who We Are

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#130]
Create a title page for "Who We Are"

Stock photo: https://3.basecamp.com/4474129/buckets/16925967/uploads/2774261058

List of campuses: https://3.basecamp.com/4474129/buckets/16925967/google_documents/2757687127 (Under campuses)

Campus photos: https://3.basecamp.com/4474129/buckets/16925967/vaults/2774283375

- [x] Who We Are>Vision/Mission Statement
- [x] Who We Are>Who We Are copy
- [x] Who We Are>Campus List (incomplete--rest to be added v1.1)
- [x] Who We Are>Stock photo
- [ ]  Make sure campus images are not copyrighted.

**Comment by JonSEng** [comment]
Blocked on Christine Gonzaga and others getting us the content and assets.
cc @lillyglin

**Comment by douglaschan32167** [comment]
The list of campuses seems set and we have images of them. Now we just need to make sure the images aren't copyrighted. @lillyglin is there a good way of doing that?

**Comment by lillyglin** [comment]
@jessewoo I am assuming that...you have been working on this. :x

**Comment by lillyglin** [comment]
@douglaschan32167 List of campuses are actually still WIP.

For images, we're going to have to scour the university websites to see if they have brand guidelines and free-to-use image libraries. e.g. https://ucpa.ucsd.edu/resources/image-library. I'll probably have to do that. ;-;

**Comment by jessewoo** [comment]
sure, i'll need images...I just googled those images and cropped it myself. 

So we can't use these images?
![image](https://user-images.githubusercontent.com/12104578/85100123-29b24500-b1b4-11ea-93ba-106caa05397a.png)

**Comment by lillyglin** [comment]
@jessewoo Unfortunately no, especially if they're done for editorials--those are mucho expensive. I'm gonna have to go to all the university websites and find their free to use images. ;-----;

**Comment by lillyglin** [comment]
@jessewoo Campus photos up! https://3.basecamp.com/4474129/buckets/16925967/vaults/2774283375

(Just missing UMN)
