### ISSUE TITLE
Header/Footer: Social Media Icons

### ISSUE THREAD

**Issue by iksoosong** [International-Mentorship-ISMP/ismp#132]
Get the new social media icons and add them to the footer and header according to the design
https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=153%3A603

Please also link to our wechat (QR code not in scope for V1). Ask Dustin Chen for the WeChat link

**Comment by vickyadebona** [comment]
@lillyglin Can you post the social media links here? Thanks :D

**Comment by lillyglin** [comment]
@vickyadebona 
FB: https://www.facebook.com/internationalmentorship
IG: https://www.instagram.com/internationalmentorship/

What's what we have so far :x

**Comment by douglaschan32167** [comment]
@vickyadebona https://www.linkedin.com/company/internationalmentorship
LinkedIn

**Comment by vickyadebona** [comment]
@douglaschan32167 @lillyglin should the LinkedIn link be added to the header and footer or just the footer? And then I would also need a matching LinkedIn icon

**Comment by lillyglin** [comment]
@vickyadebona Yes please! Header and footer. Do you need help finding the LinkedIn icon?

**Comment by vickyadebona** [comment]
@lillyglin yeah, I need help finding one that matches the other icons :)

**Comment by vickyadebona** [comment]
@lillyglin nevermind, I was able to figure out the linkedIn icon :)
