### ISSUE TITLE
About Us - Leadership

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#133]
- [x] Subpage: Leadership
- [x] Headshots
- [ ] Bios

**Comment by JonSEng** [comment]
This is blocked headshots and bios

**Comment by lillyglin** [comment]
@jessewoo here we go: https://3.basecamp.com/4474129/buckets/16925967/todos/2757514395

We didn't collect all of them, but just the ones we found grainy or incorrect proportion. Do we need all?

**Comment by douglaschan32167** [comment]
Going to move this to selected for development. Feel free to move it back to blocked if you add what you can and then still need more photos.

**Comment by lillyglin** [comment]
@douglaschan32167 @jessewoo Bump for update. Anything after (I believe) June 21st has been moved to updated to August 15.
