### ISSUE TITLE
Format the 2-3 blogposts from the content team

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#136]
Once we get it. Put it into our website, to be shown on a blogpost rendering page.

- [x] Format Housing options
https://docs.google.com/document/d/1KiurUmGG016tLOIPqD4D7MlpAxLWouKtagYlTZMLfRs/edit

- [x] Format Online Class Tips 
https://docs.google.com/document/d/1lGo53bzwqOiUIF_FWeEfWN9iqZxSBFMx146o5W7cRIQ/edit

- [x] Format Ways to manage your loneliness
https://3.basecamp.com/4474129/buckets/16925967/google_documents/2774217860

- [x] Replace the header image for where to live in college

- [x] Replace the header and thumbnail image for online classes
https://3.basecamp.com/4474129/buckets/16925967/google_documents/2757606263#__recording_2774226175

- [ ] Format another blogpost if we get one.

For the images, host them in S3 by uploading them via the s3 console. If you copy-paste from a google doc, the pictures will be by default hosted by google, so we don't know if people can see it from China. Just to be safe, re-upload them in s3 and change the url using the editor.

Please also save the newly created blogposts in fixtures. To do this:

1). Use the backend admin portal to create the blogpost. (can bug @douglaschan32167  for credentials). Make sure to hit save.
2).  Hit the backend api call. http://localhost:8000/api/v1/blogpost http://localhost:8000/api/v1/blogpostcontent. These should give you lists of json objects, including the blogpost and blogpostcontent you just created. You can also look at localhost:3000/blog-list and make sure the blogpost is listed there.
3). Open backend/api/blogpost/fixtures/blogpost.json and record the json of the blogpost you just created. Copy the syntax of the existing blogposts.
4). Open backend/api/blogpost_content/fixtures/blogpostcontent.json and record the new blogpostcontent you just created. Copy the syntax of the existing entries.
5). Run `sudo docker-compose down -v --remove-orphans`. This will get rid of your database.
6). Run `docker-compose up`. Once this is up, go to localhost:3000/blog-list and make sure the blogpost you entered is listed there. Click on it and make sure the blog page looks okay.
7). Commit your changes and make a PR.

Once all the received blogs are formatted we can move this back to blocked.

To really be able to verify this, though, we need to see how it looks on the blog article page.

**Comment by douglaschan32167** [comment]
First completed blogpost: https://docs.google.com/document/d/1KiurUmGG016tLOIPqD4D7MlpAxLWouKtagYlTZMLfRs/edit

**Comment by douglaschan32167** [comment]
Received second blog: Online class tips.
https://docs.google.com/document/d/1lGo53bzwqOiUIF_FWeEfWN9iqZxSBFMx146o5W7cRIQ/edit

**Comment by douglaschan32167** [comment]
Added the first 2 to fixtures (in PR). Moving back to blocked.

**Comment by lillyglin** [comment]
@douglaschan32167 @misunchoi Blog #3 has been uploaded: https://3.basecamp.com/4474129/buckets/16925967/vaults/2758618900

**Comment by douglaschan32167** [comment]
I've formatted all 3 we have so far. Moving this to blocked in case we get more.

**Comment by kailanjian** [comment]
sorry misclicked in the project view will move it back

**Comment by vickyadebona** [comment]
@douglaschan32167 are we keeping this open + in blocked until we get all the blogposts for this release?

**Comment by lillyglin** [comment]
@douglaschan32167 Let's close this, since this is for v1. I'll add separate issues when we get new blog articles.

**Comment by douglaschan32167** [comment]
@lillyglin Sounds good
