### ISSUE TITLE
Apply: Interacts weirdly with a password manager

### ISSUE THREAD

**Issue by iksoosong** [International-Mentorship-ISMP/ismp#137]
I'm using LastPass + 1Password, and they both display weird. See the gray, faded out blob to the right of the first name field
<img width="518" alt="Screen Shot 2020-06-12 at 9 43 26 PM" src="https://user-images.githubusercontent.com/66575722/84560135-d0e73600-acf5-11ea-95fd-7f7d7afa5106.png">

**Comment by kailanjian** [comment]
this seems like a weird edge case with your setup because I have a password manager (BitWarden) but it's not broken, not sure if it's worth fixing for v1. If it's too obtrusive or prevents you from continuing we can fix it. Lmk what you think otherwise we can push it out.

**Comment by iksoosong** [comment]
It's not great but let's deprioritize it
