### ISSUE TITLE
blog: Format the 2-3 webinars from the content team.

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#138]
This will basically be a blogpost, but will have the type 'webinar'.
We will need to put this into a form that can go on a blog article page.

~~Use 2-3 of the videos and blurbs from here:~~ 
~~https://3.basecamp.com/4474129/buckets/16925967/documents/2757651014#__recording_2757651377~~

~~Youtube links to the webinars:~~
~~College admissions webinar module 1 https://youtu.be/uyN2SWiqrXw~~
~~Surviving your first week in america module 1: arriving in america https://youtu.be/MPadfytGWHM~~

To really validate this we need the blog article page.

Updated in comment.

**Comment by lillyglin** [comment]
@douglaschan32167 @misunchoi We need to replace the webinars (which were still WIP drafts) with final webinars that we've received from content. Let's get these 2 up:

- https://3.basecamp.com/4474129/buckets/16925967/google_documents/2797986752
- https://3.basecamp.com/4474129/buckets/16925967/google_documents/2797944518

*Still waiting on YT links

-[ ] Format blog article pages for webinars
-[ ] Embed YouTube links
-[ ] Include blurbs

**Comment by misunchoi** [comment]
ok I added placeholders for now, let me know if you guys want to replace the thumbnails, I just replaced it with image that I thought were relevant; in terms how we are going to display the videos, I think we can just use the embedded code from YouTube if they are uploading them

**Comment by douglaschan32167** [comment]
@misunchoi Hey Misun, did you add the json to the fixtures (backend/api/blogpost_content/fixtures/blogpost_content.json and backend/api/blogpost/fixtures/blogpost.json) as well and check it in? Otherwise we're going to lose them whenever we reboot the site you formatted them on.

**Comment by misunchoi** [comment]
oh I forgot about that, I'll make a PR for it, but I think we are still waiting for the youtube link, so I think we can hold it off until we receive the content

**Comment by douglaschan32167** [comment]
@misunchoi 
https://3.basecamp.com/4474129/buckets/16925971/todos/2734318641#__event_4363831840
https://3.basecamp.com/4474129/buckets/16925967/google_documents/2797986752#__recording_2798864048
https://3.basecamp.com/4474129/buckets/16925967/google_documents/2797944518#__recording_2798101028
Links should be in the comments by Dustin at the bottom.
