### ISSUE TITLE
Apply: Dropdown menu for countries

### ISSUE THREAD

**Issue by iksoosong** [International-Mentorship-ISMP/ismp#139]
Have a dropdown menu of countries with an Other: ____ option as well.

**Comment by douglaschan32167** [comment]
maybe we could use this? https://www.npmjs.com/package/react-country-region-selector

**Comment by JonSEng** [comment]
Hi @lillyglin is this for V1?

**Comment by douglaschan32167** [comment]
@JonSEng  Because of political issues (is Taiwan a country?) moving this to Won't do.
