### ISSUE TITLE
Application Form Workflow

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#14]
https://trello.com/c/Jr9UdCFq/7-application-form-workflow

https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=3%3A2

localhost:3000/application-form

- [x] Can Click submit to create application in db
- [x] Application Step 2 (Academic Information)
- [x] validation errors (onBlur ?)
- [x] "Apply Now" button opens Application Step 1 (Personal Information)
- [x] Application Step 3 (Mentorship Interest)
- [x] FE: Completion Page
- [x] FE: Fix Date picker
- [x] FE: Change links to point to /apply instead of /application-form
- [x] BE: Change API endpoint to /application or /apply instead of /applicationForm (no camel-case...ugh)
- [x] FE: Change API endpoint to new endpoint chosen by BE
- [x] Datepicker sizing is weird, doesn't match others when window is small, make it consistent
- [x] Doesn't trigger validation onBlur() (actually onBlur() looks like it doesn't actually work) even though on the docs it says it's supported, make sure it triggers onBlur
- [x] it's possible to type in a date and the value will be undefined, make it so that any input is always validated
- [x] only consistent way it works is when the datepicker actually opens the calendar, make it so either you have to use the date picker, or even better, it looks at the input box for values.
- [x] update forms to match requirements

**Comment by douglaschan32167** [comment]
Are more issues, but will close this issue and create others. #150 #153
