### ISSUE TITLE
Mentors Page - Campus Director Cards

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#143]
- [ ] Campus Director cards
- [ ] Campus Director cards>headshot
- [ ] Campus Director cards>copy
- [ ] Campus Director cards>emails
- [ ] Get finalized design for 3 column layout

## Style
Either h3 or h4 under name "campus director". include emailto: ref at bottom of their info.

Emails for campus directors (missing some campuses): https://3.basecamp.com/4474129/buckets/16925967/google_documents/2757687127

**Comment by douglaschan32167** [comment]
List of campus directors is here
https://docs.google.com/spreadsheets/d/1bjwcQv3gHALI_ZM2M7Rog_GknU_cxC41kPCfO14AFsM/edit#gid=1150309823
We can start populating the site and then move it back to blocked later to await more data.

**Comment by JonSEng** [comment]
Needing clarification https://3.basecamp.com/4474129/buckets/16925967/todos/2777778247

**Comment by JonSEng** [comment]
Scoped https://3.basecamp.com/4474129/buckets/16925967/todos/2777778247#__recording_2777807310
