### ISSUE TITLE
Client Side Filtering by Campus

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#144]
Search mentors by campus

**Comment by JonSEng** [comment]
Hi @dougchansolute @lillyglin just wondering if this ticket is still relevant. And if so how should we label + milestone it?

**Comment by douglaschan32167** [comment]
This is like a v1.1 or 1.2 issue. We still need that functionality but it's not crucial for the v1 because we don't have the page that shows the mentors for a specific campus yet. Maybe v2, frontend, backend, comp/mentors?

**Comment by JonSEng** [comment]
This is closer to what the V1 scope is. Post V1 we will add tickets later as we shape work.

**Comment by douglaschan32167** [comment]
This seems to be done.
