### ISSUE TITLE
Application Form - MailChimp send to application contacts based on location field

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#145]
Form results to send to ~~regional directors~~ application contacts (per campus) conditional on "location" field. Sent via MailChimp

Campus contacts found here: https://3.basecamp.com/4474129/buckets/16925967/google_documents/2757687127 (Under contact info tab>application contacts)
 
Final list for v1.

**Comment by douglaschan32167** [comment]
Working with Dustin on this. May require some  refactoring of app form so moving it to blocked for now.

**Comment by lillyglin** [comment]
@douglaschan32167 Updated with doc.

**Comment by lillyglin** [comment]
@douglaschan32167 I've set this as final list for v1. Moving out of block.

**Comment by douglaschan32167** [comment]
This is all up to the Marketing people now. I've given them all the info they need. Moving this to done.
