### ISSUE TITLE
Application Form - Copy for basic overview of application

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#146]
Copywriting content overview of the ISMP application (letting applicants know what how our program works)

**Comment by JonSEng** [comment]
hi @lillyglin can you clarify what this means?

Per the Google Doc:

MVP | 2 | Copy | Copy for basic overview of application
-- | -- | -- | --

**Comment by lillyglin** [comment]
@JonSEng copy = copywriting. content basically.

**Comment by kailanjian** [comment]
I used what was written in the figma, if we need to make changes we can otherwise let's close this: 
![image](https://user-images.githubusercontent.com/3068323/84585125-37855600-adc1-11ea-957f-e058feb1b530.png)

**Comment by lillyglin** [comment]
@kailanjian We have updated copywriting for that part! https://3.basecamp.com/4474129/buckets/16925967/documents/2746721319
