### ISSUE TITLE
Color Redesign

### ISSUE THREAD

**Issue by iksoosong** [International-Mentorship-ISMP/ismp#147]
We want to redo the colors for our website. Scope not currently determined. Awaiting design before we decide what we want to include in the scope of V1. 

Newest colors from branding & marketing are here: https://3.basecamp.com/4474129/buckets/16925973/documents/2737648639#__recording_2757704997

**Comment by lillyglin** [comment]
Waiting on marketing and branding. https://3.basecamp.com/4474129/buckets/16925973/uploads/2737646249#__recording_2754316053

**Comment by lillyglin** [comment]
@iksoosong Moving this over to v1.1. New colors can be found in branding guidelines here: https://www.dropbox.com/s/thgn2rk04xgy5n3/ISMP_Branding%20Guideline_062020_esalvador.pdf?dl=0
