### ISSUE TITLE
code of conduct: Create page

### ISSUE THREAD

**Issue by iksoosong** [International-Mentorship-ISMP/ismp#149]
Create a code of conduct page and link it in the footer next to where the privacy and terms of service pages are
Code of conduct language: https://drive.google.com/file/d/1-Q-JjM_gUU4JtpLeVhNArvRZsAiEU1kh/view?usp=sharing

**Comment by iksoosong** [comment]
We're currently blocked on the content from Jacob Chang
@lillyglin fyi, in case you want to link the basecamp TODO to this ticket.

**Comment by douglaschan32167** [comment]
We received the document (see description). Moving this to  selected for dev.
