### ISSUE TITLE
Application form frontend content changes

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#150]
Making this one ticket because these all have to be done together or things will break.
- [x] Only ask for birth year, not entire birthday.
- [x] Make county/state non-required field
- [x] Remove phone number completely

- [x] Backend should remove/make optional these fields

**Comment by douglaschan32167** [comment]
@kailanjian gets first dibs if he wants this

**Comment by kailanjian** [comment]
Yep I would prefer to work on this but lmk if any of you want to help with ApplicationForm stuff. Mainly been trying to power through it myself to avoid merge conflicts and the like

**Comment by kailanjian** [comment]
@douglaschan32167 what do you mean by "make country/state non-required" (I am assuming county is a typo)? There is country of origin, should that be optional, or is this just in regards to the country and state of their school?

**Comment by douglaschan32167** [comment]
@kailanjian Sorry, I guess it's now called "School State/Province". That's the field I wanted to make optional because I don't think all countries would have states or provinces.
