### ISSUE TITLE
Application form legal agreement checkboxes

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#153]
- [x] check box for terms + conditions

- [x] check box for privacy policy

- [x] check box for code of conduct

- [x] Don't let them submit if checks not checked

Legal agreements.

**Comment by jessewoo** [comment]
gave it to the mang..

**Comment by kailanjian** [comment]
@douglaschan32167 I made a single check box for terms and conditions and privacy policy, should I make another for code of conduct?

**Comment by kailanjian** [comment]
done!
