### ISSUE TITLE
Home: Display stats of our mentors

### ISSUE THREAD

**Issue by iksoosong** [International-Mentorship-ISMP/ismp#155]
We (possibly) want to display the stats of our mentors on our home page. Design will look at it first and take a stab at it and we'll see what the feedback is on it.

**Comment by lillyglin** [comment]
Not within scope for v1. Moving over to v1.1

**Comment by douglaschan32167** [comment]
Mentor stats can be found here
]https://3.basecamp.com/4474129/buckets/16925967/google_documents/2757836559#__recording_2777884856
