### ISSUE TITLE
Home: populate testimonial cards with actual testimonials

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#167]
https://3.basecamp.com/4474129/buckets/16925967/google_documents/2757687127
Use Stella, Gabi, Taiga.

**Comment by douglaschan32167** [comment]
We have pictures for the testimonials.
https://3.basecamp.com/4474129/buckets/16925967/messages/2757584087
Still blocked until we get the actual testimonials.

**Comment by douglaschan32167** [comment]
Testimonials are starting to be populated here.
https://docs.google.com/spreadsheets/d/1bjwcQv3gHALI_ZM2M7Rog_GknU_cxC41kPCfO14AFsM/edit#gid=842785377

Moving this back to ready for dev because we have enough to get started.

**Comment by kailanjian** [comment]
seems like actually https://github.com/International-Mentorship-ISMP/ismp/pull/192 fixes this

**Comment by douglaschan32167** [comment]
Just missing Taiga's photo. Made a separate ticket for that so closing this.
