### ISSUE TITLE
[LOW PRIORITY] make testimonial cards into a carousel

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#169]
Do not even attempt this until the testimonial cards are merged into master.
There's been a request to make it a carousel but it's something that is not a big deal so don't prioritize it over other work.
I'm going to put this in blocked until the testimonial cards get merged into master.

- [ ] Expand number of testimonials to >3.

- [ ] Implement carousel (we may already have one under components. See if that works).

**Comment by JonSEng** [comment]
Hi @lillyglin @iksoosong did we decide on this? I don't remember us agreeing that we should do a carousel despite the ask per [meeting](https://3.basecamp.com/4474129/buckets/16925967/documents/2757786398).

**Comment by iksoosong** [comment]
we talked about not doing this for the schools. didn't talk about not having the carousel for testimonials.

**Comment by JonSEng** [comment]
> we talked about not doing this for the schools. didn't talk about not having the carousel for testimonials.

Yeah that's true. I thought the conversation had the tone of asking about how we're going to decide whether their solutions are what we actually want to implement.
There's a problem, they want the website to be a certain way, but this may not be the solution.
I'm assuming this if from them but not sure.

**Comment by lillyglin** [comment]
@JonSEng I think it was from one of our many meetings last week. 

For the carousel on testimonials, I nixed it for v1, just keeping to 3 testimonials for homepage. The goal for the testimonial carousel is to feature A BUNCH of testimonials (which...might not be the best idea), but let's move that to a later discussion.
