### ISSUE TITLE
Board of Directors, Officer page

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#17]
Link to Figma:
https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=576%3A746

- [x] FE: Leadership card (image + name, title, and description)
- [x] FE: Page layout
- [x] Create JSON object for profiles an CDN URLs to headshots

**Comment by douglaschan32167** [comment]
@jessewoo New requirement: 2-column grid layout instead of single-column.

**Comment by jessewoo** [comment]
@richyen - where is the s3 cdn where we can push images to.
