### ISSUE TITLE
Blogs: Render html in the frontend

### ISSUE THREAD

**Issue by iksoosong** [International-Mentorship-ISMP/ismp#181]
Can use `<td dangerouslySetInnerHTML={{__html: blog.body_content}} />` in order to render html in stringified form. Also need to do some styling after looking at it rendered.

**Comment by dbtung** [comment]
It looks like we are using https://www.npmjs.com/package/react-html-parser in `RenderBlog.jsx` - seems like it probably does the job?

**Comment by vickyadebona** [comment]
@dbtung @iksoosong yeah, we're already using `[react-html-parser](https://www.npmjs.com/package/react-html-parser)` for rendering blog html. I think we can close this.
