### ISSUE TITLE
Implement Featured Blog Articles response at /blogpost/featured

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#19]
https://trello.com/c/o6DOyLV3/58-implement-featured-blog-articles-response-at-blogpost-featured

**Comment by douglaschan32167** [comment]
This is done. The endpoint is /api/v1/blogpostcontent/?featured=true, but it has an object in agent.js that people can use, so for the most part they don't have to worry about the specifics of the endpoint.
