### ISSUE TITLE
Homepage Revamp

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#21]
https://trello.com/c/dtfgG0GQ/21-homepage-revamp

Link to Figma:
https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=303%3A134

- [x] FE: Webinar Highlights component - in progress - @samdkuo 
- [x] FE: Featured Blog Articles component (REST call to /blogpost/featured) edit: since on launch we will only have ~4 blogposts, just use /api/v1/blogpostcontent?published=true and grab the first 3 results instead of worry about featured.
- [ ] FE: Intro Video View: Include both lightbox for fullscreen view and play at original size
- [ ]  FE: Testimonials slider (3-4 student photos with quotes). DC-We should split this off into another issue once the v1 board is more set.

**Comment by douglaschan32167** [comment]
Language of the homepage:
https://docs.google.com/document/d/1WsMOlDolE-ZnYahivSbQVGRhN2NtWKJCkXeF1V1AwWw/edit

**Comment by douglaschan32167** [comment]
The UI has changed. Be sure to check the figma.

**Comment by douglaschan32167** [comment]
Moving this to #128 #131
