### ISSUE TITLE
Internationalize the application form

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#221]
**Description**
We need it to be able to be translated to chinese for the v1. We don't have the translations yet, but we can still put in the english translation strings and then move this to blocked.
Need to discuss if we should translate the help portion on the right.

Some of the translation strings can be found here. 
https://docs.google.com/document/d/1ssRT47aA0BVtNZLXf0IzQw3khM4plsA6JzdD6xiY3EM/edit

- [x] change it to read english translation strings from i18next
- [ ] Add in the chinese translation strings once we have them

**Comment by douglaschan32167** [comment]
@kailanjian Here's at least some of the chinese translations you can fill in
https://docs.google.com/document/d/1ssRT47aA0BVtNZLXf0IzQw3khM4plsA6JzdD6xiY3EM/edit

**Comment by lillyglin** [comment]
@kailanjian I'm throwing this back to you. We have translation for body 1-3. Let me get the translation for Important Info title.

https://3.basecamp.com/4474129/buckets/16925967/documents/2746721319
