### ISSUE TITLE
Make US School in Application Form a dropdown with an Other option

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#225]
**Description**
Currently it is a text input. If we make it a dropdown with an Other option, if someone from one of our schools. The benefit of this is that when we send this information to mailchimp, it will standardize the input so that it knows to send an email to the UCSD director without having to check all varitions of UCSD, ucsd, University of California San Diego, etc. 

The "other" option will cause a text field to open up, and if their school is not in our list we can still get that information. 

- [ ] US School field is a dropdown
- [ ] Selecting other opens up a text field
- [ ] Make a ticket or bug @douglaschan32167  about adjusting mailchimp based off of these changes.

**Comment by JonSEng** [comment]
Building on this, idea is that we build up a list of official schools for auto-complete but also accepts a custom input.

**Comment by kailanjian** [comment]
I feel like this may be pretty useful and I'm willing to work on this for v1 instead of the bugs, if someone can get me a list of schools we want to officially include

**Comment by douglaschan32167** [comment]
@kailanjian  https://docs.google.com/spreadsheets/d/1bjwcQv3gHALI_ZM2M7Rog_GknU_cxC41kPCfO14AFsM/edit#gid=0
Look in the campuses tab. 

If this ends up taking up too much time, an alternative Dustin suggested is to just add a line that says to write out the full name of your school instead of an abbreviation. That would require internationalizing but would be less work. It's up to you.
