### ISSUE TITLE
Korean Home Page Translation

### ISSUE THREAD

**Issue by lillyglin** [International-Mentorship-ISMP/ismp#226]
**Description**
Korean Home Page Translation. Both content and web strings have been sent over for translation.

Translations are housed here: https://3.basecamp.com/4474129/buckets/16925967/vaults/2774213712
- [ ] Korean translation (content only)
- [ ] Korean web string translation

**Comment by douglaschan32167** [comment]
@lillyglin I thought we were only doing chinese and english for the v1? Did that change?
