### ISSUE TITLE
Application form: remove fee copywriting

### ISSUE THREAD

**Issue by lillyglin** [International-Mentorship-ISMP/ismp#229]
We're no longer collecting fees for ISMP. Please remove from application form page.

THANKS @kailanjian !

**Comment by kailanjian** [comment]
![image](https://user-images.githubusercontent.com/3068323/85101683-cde9bb00-b1b7-11ea-8129-08c5df857ea2.png)

Hi @lillyglin I think latest version should have the correct copy, lmk if this is not correct, otherwise we can close!

**Comment by lillyglin** [comment]
@kailanjian Awesome. Closing.
