### ISSUE TITLE
Tags DB and API

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#23]
https://trello.com/c/dyFLilWj/13-tags-db-and-api

Only working in backend

- [x] Backend: support tags
- [x] Backend: take tags as part of blogpost content
- [x] frontend add tags as part of blogpost object that gets saved in api call

**Comment by richyen** [comment]
- [ ] Backend: support tags
- [ ] Backend: take tags as part of blogpost content
- [ ] frontend add tags as part of blogpost object that gets saved in api call

**Comment by douglaschan32167** [comment]
Since blogposts go through the backend, this is done for v1.
