### ISSUE TITLE
Homepage: replace hero image

### ISSUE THREAD

**Issue by lillyglin** [International-Mentorship-ISMP/ismp#235]
Replace current old hero image on homepage with following:

https://3.basecamp.com/4474129/buckets/16925967/uploads/2774270618

**Comment by JonSEng** [comment]
As a result of our [image hosting solution](https://3.basecamp.com/4474129/buckets/16925967/messages/2774323209#__recording_2777877082)

Blocked on: https://github.com/International-Mentorship-ISMP/ismp/issues/264

**Comment by douglaschan32167** [comment]
I think this is unblocked? Moving it to selected for development
