### ISSUE TITLE
Add Recommended Articles Section to Blog Article Page

### ISSUE THREAD

**Issue by vickyadebona** [International-Mentorship-ISMP/ismp#246]
**Description**
Currently, the page that renders a blog article is missing the recommended blog section on the bottom.

https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=303%3A469

- [x] I've added the proper component `comp/*` label + other labels
- [x] I've added any context to where the decision was made (Basecamp links...etc.)

**Comment by vickyadebona** [comment]
@douglaschan32167 since we don't have an endpoint for recommended articles, I'm thinking to just do the three most recent articles under the same category as the current article you're reading. If there are less than three related articles, then I think the most recent one or two are fine.  

I'll also have it where if the current article is the only article in that category, then it just won't show the recommended articles component at all. What do you think?

**Comment by douglaschan32167** [comment]
@vickyadebona That sounds good. Or we could just show the 3 most recent blogposts (possibly besides the one being shown on the blog article page).
I like your way better but I'm just not sure how much we will have things labeled by categories for the v1. I say we do it your way though that way we don't have to go back and change it.
