### ISSUE TITLE
Not easy to tell we can filter by campus in mentor page

### ISSUE THREAD

**Issue by iksoosong** [International-Mentorship-ISMP/ismp#248]
It's not easy to tell that we can filter by mentors. It's a very light color so doesn't provide much contrast to the background, and it's all the way on the far right when the mentors start on the left. 

I would also recommend having the first row be a campus with 3 people. 

<img width="2990" alt="Screen Shot 2020-06-20 at 10 25 28 AM" src="https://user-images.githubusercontent.com/66575722/85207806-5f544c80-b2e0-11ea-810c-d0ec11023499.png">

Tested on Chrome on MacOs

**Comment by dbtung** [comment]
Fixed by #346
