### ISSUE TITLE
We have the apply now button in many places

### ISSUE THREAD

**Issue by iksoosong** [International-Mentorship-ISMP/ismp#249]
**Describe the bug**
We have the "Apply Now" button in many places on the page, depending on which page the user navigates to. Is this expected?

**To Reproduce**
Scroll down on the /about page

**Expected behavior**
Not so many "Apply Now"s? Maybe get rid of it in the footer given that the header is sticky and has the button?

**Screenshots**
<img width="2986" alt="Screen Shot 2020-06-20 at 10 29 10 AM" src="https://user-images.githubusercontent.com/66575722/85207985-a1ca5900-b2e1-11ea-8f75-1d70a1052615.png">

**Comment by douglaschan32167** [comment]
According to @lillyglin, being obnoxious gets results. I'll let her comment on this.

**Comment by lillyglin** [comment]
@iksoosong From a marketing perspective, lots of CTAs = good thing. Actionable in your face is what gets results (as @douglaschan32167 said).

Let me know your thoughts.

**Comment by iksoosong** [comment]
I just created a ticket because it stood out to me. I agree that this probably(?) will drive metrics. I think there's bound be some tension between marketing and UI/UX. If we decided we want to keep this, that sounds okay to me.

**Comment by lillyglin** [comment]
@iksoosong Yeah, I know what you mean, but gotta go where the leads come in.
