### ISSUE TITLE
Program/Syllabus/Topics Page

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#25]
https://trello.com/c/0dflGrgW/51-program-syllabus-topics-page

Link to Figma:
https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=492%3A243

- [ ] FE: Implement "Category Card" component
- [x] BE: Implement REST API call to Program Topics
- [ ] FE: Ask API for Program Topics and list them out in 2-column format

**Comment by richyen** [comment]
- [ ] FE: Implement "Category Card" component
- [ ] BE: Implement REST API call to Program Topics
- [ ] FE: Ask API for Program Topics and list them out in 2-column format

**Comment by douglaschan32167** [comment]
Sorry @jessewoo , they changed the UI, so you may have to go back and change your PR.
https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=492%3A243
