### ISSUE TITLE
Mentors - add in headshots

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#256]
**Description**
Add in headshots for all the mentors.

~~This is blocked on this [todo](https://3.basecamp.com/4474129/buckets/16925967/todos/2770510087#__recording_2774316940) on the Content Team.~~

Updated headshots: https://3.basecamp.com/4474129/buckets/16925967/cloud_files/2778154641

- [x] I've added the proper component `comp/*` label + other labels
- [x] I've added any context to where the decision was made (Basecamp links...etc.)

**Comment by lillyglin** [comment]
@JonSEng I've marked this out as ready for development. We're missing some people's headshots, but at this point, that'll have to be it for now.

**Comment by lillyglin** [comment]
@kailanjian We've got updated headshots for:

- [ ] Annie Glass

- [ ] Henry Chen

- [ ] Larry Tan
