### ISSUE TITLE
Mentors Page - add in descriptions

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#257]
**Description**
Fill in missing descriptions for each mentor. Namely:
1. Name
1. Education
1. LinkedIn
1. Current Job

<img width="494" alt="Screenshot 2020-06-20 12 03 41" src="https://user-images.githubusercontent.com/1644269/85209604-16a39000-b2ee-11ea-9eee-b3d89f70e35a.png">

Is an example of what we want.

- [x] I've added the proper component `comp/*` label + other labels
- [x] I've added any context to where the decision was made (Basecamp links...etc.)

~~Blocked by [todo](https://3.basecamp.com/4474129/buckets/16925967/todos/2777766446).~~

Based on BC, we're using only *complete* and *uploaded images* as of latest. Any missing information, don't show.

Requirements:
1. Show only completed profiles per ISMP Management g-sheet.
2. Comment out any incomplete mentor cards that have placeholder images or descriptions.

**Comment by lillyglin** [comment]
@JonSEng Final photos are here: https://3.basecamp.com/4474129/buckets/16925967/todos/2770510087#__recording_2793908758

Any photos that are missing or bad quality, please comment out. They're not showing up on website by launch.

**Comment by douglaschan32167** [comment]
Seems to be done. Closing issue
