### ISSUE TITLE
Tidy up Mentors Page

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#259]
**Description**
After all the mentors content is in, we'll need to do a spike to see what tidying is left to be done. This is a placeholder to make sure we have slack accounted for as we look at our board.

- [ ] I've added the proper component `comp/*` label + other labels
- [ ] I've added any context to where the decision was made (Basecamp links...etc.)

**Comment by dbtung** [comment]
What exactly does tidying up the mentors page entail?
