### ISSUE TITLE
[BUG] Privacy Policy Page has not been updated to match latest i18n

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#269]
**Describe the bug**
The privacy policy page looks like this 
![image](https://user-images.githubusercontent.com/1157135/85218855-302af300-b353-11ea-94ba-21e26d9908ee.png)

- [x] I've added the proper component `comp/*` label + other labels

**To Reproduce**
URL or Steps to reproduce the behavior:
1. Go to the footer
2. Click on Privacy Policy
3. You will see it.

**Expected behavior**
It should show the text of the privacy policy (frontend/public/locales/en/privacy-policy.json)

**Screenshots**
![image](https://user-images.githubusercontent.com/1157135/85218884-69fbf980-b353-11ea-8e89-3443e8c46753.png)

**Comment by misunchoi** [comment]
looks like this has been fixed already 
<img width="1034" alt="Screen Shot 2020-06-25 at 9 29 11 PM" src="https://user-images.githubusercontent.com/43766700/85820368-f0855200-b72a-11ea-83aa-b278c241b38b.png">
