### ISSUE TITLE
UX Tasks

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#27]
https://trello.com/c/aitgXEd4/55-ux-tasks

This is the area for UX team to communicate to us what changes have been created (i.e., additions to Figma, etc.)

Please create a checklist item, and Richard/Doug will mark it as "completed" once the item has been added to a Card for dev team to work on (or added as an checklist item to an existing Card)

**Comment by JonSEng** [comment]
Hi @richyen is this ticket still needed? It seems to be a general catch all for shaping UX work.

**Comment by richyen** [comment]
> Hi @richyen is this ticket still needed? It seems to be a general catch all for shaping UX work.

Probably not needed.  In Trello it was originally intended as a way for UX team to trigger us to look at figma for changes, then create new cards for to-do items
