### ISSUE TITLE
Legal documents need bracketed info to be filled out

### ISSUE THREAD

**Issue by kailanjian** [International-Mentorship-ISMP/ismp#271]
Example:
![image](https://user-images.githubusercontent.com/3068323/85219686-b434a900-b35a-11ea-9b36-9cf38e5b47ec.png)

- [ ] get official urls to put in url brackets:
- [ ] get contact email: 
- [ ] replace brackets in i18n files with those for terms of use
- [ ] replace for privacy policy

**Comment by douglaschan32167** [comment]
This is absolutely needed for the v1

**Comment by douglaschan32167** [comment]
I'm going to move this to blocked so it's clear that we want to work on it but need more info.

**Comment by kailanjian** [comment]
Here is a list of all the brackets:
**Privacy Policy**
[ ] -   "Our Website and the ISMP Program are not intended for children under 13 years of age ... If you believe we might have any information from or about a child under 13, please contact us at [CONTACT INFORMATION]."
[ ] - "To ask questions or comment about this privacy policy and our privacy practices, contact us at: [EMAIL ADDRESS]."

**Terms of Use**
[ ] - "Please read the Terms of Use ... abide by these Terms of Use and our Privacy Policy, found at [PRIVACY POLICY URL], incorporated herein by reference..."
[ ] -  "To access the Website ... Privacy Policy [LINK TO PRIVACY POLICY], and you consent to all actions we take with respect to your information consistent with our Privacy Policy."
[ ] - These Terms of Use permit you ... other than that set out in this section, please address your request to: [EMAIL ADDRESS]."
[ ] - Our designated copyright agent to receive DMCA Notices is:",
     Jacob Chang
     International Student Mentorship Program
     7271 Enders Ave
     San Diego, CA 92122
     [EMAIL ADDRESS]

**Comment by douglaschan32167** [comment]
Thanks @kailanjian ! Moving this to selected for development
