### ISSUE TITLE
Display auto-detected user language

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#275]
**Description**
Use https://www.i18next.com/overview/plugins-and-utils#language-detector to automatically display.
Typically these are done through the language locale in the header.

[Linked BC Task](https://3.basecamp.com/4474129/buckets/16925967/todos/2778568218).

One way to test this out locally:
1. Setting locale to `zh`. I validated this by looking at my network requests (I'm not 100% sure which requests to look out for in our react app) to make sure I was requesting `zh` (I used [`Locale Switcher`](https://chrome.google.com/webstore/detail/locale-switcher/kngfjpghaokedippaapkfihdlmmlafcc) to change the locale. 
<img width="1334" alt="Screenshot 2020-06-21 14 33 34" src="https://user-images.githubusercontent.com/1644269/85235748-5476e600-b3cc-11ea-95e0-d271ceb8d2ed.png">

2. See if it displayed the expected text.

- [ ] I've added the proper component `comp/*` label + other labels
- [ ] I've added any context to where the decision was made (Basecamp links...etc.)

**Comment by JonSEng** [comment]
cc @lillyglin would this be for V1? I would imagine so.

**Comment by lillyglin** [comment]
@JonSEng Responded to you on BC
