### ISSUE TITLE
Mentor Profiles DB and API

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#30]
https://trello.com/c/mzJQ0BUO/5-mentor-profiles-db-and-api

**Comment by douglaschan32167** [comment]
Reopening this ticket based on new requirements.

- [ ] Add mentor about me field to db.

- [ ] add a foreign key to school table associating a mentor as a campus director.

- [ ] add contact email for mentors. This is a hack but we can change it later.
