### ISSUE TITLE
Make google tag manager ID in src/index.js read from environment variable

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#306]
**Description**
So that we don't have to change the code but instead can set the env var in docker-compose.yml.
This decision was made in my head.

- [x] I've added the proper component `comp/*` label + other labels
- [x] I've added any context to where the decision was made (Basecamp links...etc.)

**Comment by iksoosong** [comment]
I've been thinking about this, and I wonder if we actually have to keep this secret. It's going to be visible by anyone that looks at the source anyway

**Comment by iksoosong** [comment]
As far as I can tell, the most malicious thing they can do is to send their own data to our GTM account

**Comment by iksoosong** [comment]
@douglaschan32167 looks like we can just insert it into the code directly. Without react, you usually just add this script at the top which has the GTM ID hardcoded in there: https://developers.google.com/tag-manager/quickstart
Lmk if you have different thoughts, but I think we can just hardcode it and leave it at that. Wdyt?

**Comment by douglaschan32167** [comment]
Sure, let's just hardcode it.
