### ISSUE TITLE
[BUG] gap between get connected with a mentor and footer on blog article page

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#308]
**Describe the bug**
<img width="2046" alt="Screenshot 2020-06-27 10 18 17" src="https://user-images.githubusercontent.com/1644269/85928149-b9648d00-b85f-11ea-8907-43efa9f86ca6.png">

- [ ] I've added the proper component `comp/*` label + other labels

**To Reproduce**
URL or Steps to reproduce the behavior:
1. Go to any blog article
3. Scroll down to bottom
4. See gap

**Expected behavior**
no gap
**Screenshots**

**Optional: Desktop (please complete the following information):**

**Optional: Smartphone (please complete the following information):**

**Comment by richyen** [comment]
is this really a bug, or just a test? I only see boilerplate stuff in here 🤷‍♂️

**Comment by misunchoi** [comment]
looks like there's supposed to be recommended blogposts between those blocks https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=303%3A469

I can remove that gap for now since looks like we are not implementing recommended blogposts for v1?
