### ISSUE TITLE
Mentor Login Page, using authentication API

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#31]
https://trello.com/c/uKkTI4Mc/20-mentor-login-page-using-authentication-api

**Comment by jessewoo** [comment]
@paulog11 is actually working on it.

**Comment by pddang** [comment]
@jessewoo  @paulog11 is working on authentication with google mail. I am working on it on the Django backend side.

**Comment by jessewoo** [comment]
@paulog11 is busy I think because of mission trip. @pddang - how's progress on this task?

**Comment by pddang** [comment]
It’s done. Merged to the master branch!

**Comment by JonSEng** [comment]
Hi @pddang would you be able to link the PR(s) to this issue when you get a chance? I couldn't by name figure out which commit might be the related one https://github.com/International-Mentorship-ISMP/ismp/commits/master
