### ISSUE TITLE
Make the wechat icons link to the ISMP wechat.

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#321]
**Description**
This is blocked by marketing getting us an ISMP wechat account but I'm creating a ticket so we don't forget about it.
This decision was made months ago.

- [x] I've added the proper component `comp/*` label + other labels
- [x] I've added any context to where the decision was made (Basecamp links...etc.)

**Comment by douglaschan32167** [comment]
@lillyglin we don't have the wechat link yet. Can you bug marketing about it periodically?

**Comment by vickyadebona** [comment]
@douglaschan32167 @lillyglin per Dustin's recent email, it seems that we now have an ISMP WeChat account. But getting links within WeChat to work externally is really complicated (actually, not possible), so I'm not sure if we can actually get a link that can be used in the header and footer. Seems like the only way to share the account is through QR codes. Dustin did link the QR code in his email, so we can probably squeeze that somewhere into the footer. 

So I'm wondering if we should omit the wechat icon from the header entirely and then just have the QR code in the footer?

**Comment by lillyglin** [comment]
@vickyadebona Wow, really?? They really made WeChat native mobile-only. So there's nothing to trigger opening the WeChat app? ;-;

QR code it is. We're able to get the QR code with the WeChat icon on it?

**Comment by vickyadebona** [comment]
@lillyglin the QR code that I have has the ISMP logo on it. Not sure how I would get the WeChat logo on it, but I guess we could put some text under it that says it's for WeChat

**Comment by lillyglin** [comment]
@vickyadebona Yeah let's go ahead and do that then.

**Comment by douglaschan32167** [comment]
In the future we may want to pop up a modal with a picture of a QR code on it. Not required for V1 though.

**Comment by lillyglin** [comment]
@douglaschan32167 Something to consider--the UX might be a wee bit weird, so need some more consideration for that.

**Comment by vickyadebona** [comment]
@lillyglin  @douglaschan32167 This is what I have so far:

![image](https://user-images.githubusercontent.com/64994944/87233084-412abb00-c379-11ea-976a-1e73da8fd21a.png)

mobile: 

![image](https://user-images.githubusercontent.com/64994944/87233133-a088cb00-c379-11ea-9997-c97d1c2a8245.png)

**Comment by douglaschan32167** [comment]
If we have the QR code we should take out the wechat icon/link right?

**Comment by vickyadebona** [comment]
Yeah, we would take it out

**Comment by vickyadebona** [comment]
Is the positioning ok?

**Comment by douglaschan32167** [comment]
Seems ok. I'm probably not the person to ask though. Does it make the footer too thick?

**Comment by vickyadebona** [comment]
It does, but there isn't really anything we can do about it. I could make the QR code smaller, but that would make it less visible.
