### ISSUE TITLE
[BUG] Unpublished blog articles are showing up in the blogs page

### ISSUE THREAD

**Issue by dbtung** [International-Mentorship-ISMP/ismp#356]
**Describe the bug**
Unpublished blog articles are showing up in the blogs page

- [x] I've added the proper component `comp/*` label + other labels

**To Reproduce**
URL or Steps to reproduce the behavior:
1. Go to 'http://127.0.0.1:8080/blog-list'
2. Should see three articles there
3. Examine `blogpost_content.json` and notice that two articles are published, one of the articles is published

**Expected behavior**
Only see two articles in the blog list page.

Two ways of fixing this:
- Add a query param `publish=true` to requests for blogpostcontent on the user-facing site
- Default to only returning published blogpostcontent on the backend (this is probably better)

**Screenshots**

**Optional: Desktop (please complete the following information):**

**Optional: Smartphone (please complete the following information):**

**Comment by douglaschan32167** [comment]
This is a quick backend fix. It's because the default query returns drafts too. Will fix.
