### ISSUE TITLE
[BUG] Mentors Page - Inconsistent MS vs Bachelor Degree ordering

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#375]
**Describe the bug**
Sometimes the MS appears before the Bachelor degree. e.g. Nancy Huang, Jonathan Eng, and Larry Tan's titles.

- [x] I've added the proper component `comp/*` label + other labels

**To Reproduce**
URL or Steps to reproduce the behavior:
1. Go to http://localhost:8080/mentors

**Expected behavior**
This behavior is TBD. We should establish a clear design pattern and stick with it. Ideally we can have a react component order this based on rendering logic.

**Screenshots**
<img width="434" alt="Screenshot 2020-07-07 20 55 56" src="https://user-images.githubusercontent.com/1644269/86874031-6c20c080-c094-11ea-8aa7-f47cd946bae0.png">

<img width="488" alt="Screenshot 2020-07-07 20 56 01" src="https://user-images.githubusercontent.com/1644269/86874033-6d51ed80-c094-11ea-84d3-bc849a9f3a46.png">

**Comment by douglaschan32167** [comment]
@JonSEng  How do you feel about highest degree on the top? so PhD -> M.S. -> B.S.

**Comment by JonSEng** [comment]
> @JonSEng How do you feel about highest degree on the top? so PhD -> M.S. -> B.S.

Sounds good to me!
