### ISSUE TITLE
Bug: Application: Email Address Site Input Error.

### ISSUE THREAD

**Issue by lillyglin** [International-Mentorship-ISMP/ismp#386]
https://3.basecamp.com/4474129/buckets/16925967/todos/2842737233

We're getting errors with different email address clients including: 

- @163.com. 
- @126.com. 
- @outlook.com. 
- @qq.com. 
- @sina.com. 

I'm double-checking confirmation that these particular email addresses were tested.

**Comment by JonSEng** [comment]
Redirecting Discussion back to BC
