### ISSUE TITLE
Minor Application Typos

### ISSUE THREAD

**Issue by lillyglin** [International-Mentorship-ISMP/ismp#389]
- [ ] Apply Section 2 - U.S. missing last dot https://3.basecamp.com/4474129/buckets/16925967/todos/2842748661
- [ ] Translation: [IMPORTANT] Application > Page 1 > "Next Page" should be "下一页" (currently shows “下一页t”) https://3.basecamp.com/4474129/buckets/16925967/todos/2842715209
- [ ] Apply Section 3 - "Terms and Services"  replaced with "Terms of Use" https://3.basecamp.com/4474129/buckets/16925967/todos/2842779282

**Comment by JonSEng** [comment]
Redirecting Discussion back to BC
