### ISSUE TITLE
Protect API by requiring tokens

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#39]
https://trello.com/c/WlskJ9Nz/54-protect-api-by-requiring-tokens

- [ ] Backend Make api endpoints require a token
- [ ] Frontend integrate token capability into `agent.js`

**Comment by richyen** [comment]
- [ ] Backend Make api endpoints require a token
- [ ] Frontend integrate token capability into `agent.js`

**Comment by douglaschan32167** [comment]
This may be OBE if our backend is not accepting network connections except from the frontend.
