### ISSUE TITLE
Blog post- A Short Guide On Where To Live In College> wrong post

### ISSUE THREAD

**Issue by lillyglin** [International-Mentorship-ISMP/ismp#396]
https://3.basecamp.com/4474129/buckets/16925967/todos/2842556026

After clicking on 'A Short Guide On Where To Live In College', the title of the post is correct but the actual article is the 'managing loneliness' blog.
https://staging.internationalmentorship.org/blogpost/8

**Comment by JonSEng** [comment]
https://3.basecamp.com/4474129/buckets/16925967/todos/2842556026
