### ISSUE TITLE
Blog post authors- fake author

### ISSUE THREAD

**Issue by lillyglin** [International-Mentorship-ISMP/ismp#398]
https://3.basecamp.com/4474129/buckets/16925967/todos/2842546138

- Showing up on blog list: https://staging.internationalmentorship.org/blog-list
- article: https://staging.internationalmentorship.org/blogpost/7
-article: https://staging.internationalmentorship.org/blogpost/6

**Comment by douglaschan32167** [comment]
The task is actually to remove this blogpost completely
