### ISSUE TITLE
Blog post- Mental health> wrong post/title

### ISSUE THREAD

**Issue by lillyglin** [International-Mentorship-ISMP/ismp#399]
https://3.basecamp.com/4474129/buckets/16925967/todos/2842558568

The link for the 'How To Look After Your Mental Health While Studying From Home' leads to the right blog post title page but the article below is for 'short guide on where to live in college'
 https://staging.internationalmentorship.org/blogpost/7

**Comment by JonSEng** [comment]
Redirecting Discussion back to BC
