### ISSUE TITLE
Category Card Component

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#40]
https://trello.com/c/lxSYDBf7/32-category-card-component

![image](https://user-images.githubusercontent.com/1644269/83961731-ca1a7800-a84a-11ea-9539-98009b796443.png)

**Comment by douglaschan32167** [comment]
pic: https://trello-attachments.s3.amazonaws.com/5ed294c5cd252e215387c911/5ed32d03cd5d0821b78ef51f/e0af53358a200626e714a7e82de4e3e9/image.png

**Comment by JonSEng** [comment]
Thanks @douglaschan32167 added into the description
