### ISSUE TITLE
Blog post- '3 Tips to Manage Your Loneliness' duplicate paragraphs

### ISSUE THREAD

**Issue by lillyglin** [International-Mentorship-ISMP/ismp#400]
https://3.basecamp.com/4474129/buckets/16925967/todos/2842552947

The first two paragraphs of this blog post is shown twice.
https://staging.internationalmentorship.org/blogpost/10

**Comment by lillyglin** [comment]
@douglaschan32167 If you have too much to get ready for deployment, please reassign to @misunchoi

**Comment by JonSEng** [comment]
Redirecting Discussion back to BC
