### ISSUE TITLE
Blog Search List Page

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#42]
https://trello.com/c/o4qRgOF3/33-blog-search-list-page

RY: Flagging as Duplicate of "Blog API Call" card

 

- [ ] FE: Implement Search results

 

- [ ] FE: Implement routes for blog/ (all blogposts), blog/?topic=# (where # is topic ID number, or hyphenated-topic-name), and blog/?search-term

- [ ]  FE: Pass querystring to API endpoint

**Comment by douglaschan32167** [comment]
![image](https://user-images.githubusercontent.com/1157135/83961768-37c6a400-a84b-11ea-82e6-4c41634b7bc8.png)

**Comment by jessewoo** [comment]
@misunchoi - wondering if I can take a stab at breaking this up more into components, call fake endpoints? I'll work on the master branch where your code is already merged.

**Comment by misunchoi** [comment]
@jessewoo - yeah for sure, thanks for working on it!

**Comment by jessewoo** [comment]
@misunchoi - are you still building out any other features for this? if not, i'll just start my own branch off of master.

**Comment by misunchoi** [comment]
@jessewoo no I haven't, you can work on your own branch
