### ISSUE TITLE
Categories (DB Table / API)

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#43]
https://trello.com/c/G6tDLFui/40-categories-db-table-api

@richyen : Flagging as duplicate of "Blog Landing Page"

**Comment by douglaschan32167** [comment]
![image](https://user-images.githubusercontent.com/1157135/83961793-8aa05b80-a84b-11ea-9151-3c7bae1f7c6b.png)

**Comment by douglaschan32167** [comment]
Additional tasks:

- [ ] Add description field to topics (to be shown on the program page)

**Comment by douglaschan32167** [comment]
https://github.com/International-Mentorship-ISMP/ismp/pull/80 will add the description field.

**Comment by JonSEng** [comment]
Hi @richyen @douglaschan32167 is this per the original description a duplicate of https://github.com/International-Mentorship-ISMP/ismp/issues/32 ?

**Comment by douglaschan32167** [comment]
@JonSEng This is the backend counterpart to that ticket. If we really wanted to we could combine it into one ticket, but as it stands they're not duplicates.

**Comment by douglaschan32167** [comment]
But also this is done.
