### ISSUE TITLE
Terms of Service Page

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#46]
https://trello.com/c/GZPEgRhQ/28-terms-of-service-page

Figma Link:
https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=486%3A18

Finalized Terms of Service Language:
https://drive.google.com/file/d/1udT00Bmcpw3aFQe9Xy--L8BnoMvZd2Yl/view?usp=sharing

- [x] Frontend Interface

- [x] Actual Content

**Comment by douglaschan32167** [comment]
Going to move this to blocked until we get the content from Jacob.

**Comment by douglaschan32167** [comment]
We have the finalized language.
https://drive.google.com/file/d/1udT00Bmcpw3aFQe9Xy--L8BnoMvZd2Yl/view?usp=sharing
Moving this to ready for dev

**Comment by kailanjian** [comment]
@douglaschan32167 it's got some stuff in brackets, could we get a checklist of what that stuff is supposed to map to?
