### ISSUE TITLE
Create Privacy Policy Page

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#47]
Figma Link:
https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=486%3A35

- [x] Frontend interface
- [x] Actual content

**Comment by douglaschan32167** [comment]
Going to move this to blocked until we get the content from Jacob.

**Comment by lillyglin** [comment]
@kailanjian I think this is your's.

Doc's can be found here: https://3.basecamp.com/4474129/buckets/16925967/vaults/2735687519

**Comment by kailanjian** [comment]
I may have made the trello card but I think anyone can pick this up. There should be no dependencies. I'm a bit behind on the App Form so I'm going to focus on that for now

**Comment by kailanjian** [comment]
if anyone wants to pick this up, I have code to generate a page from a `privacy-policy.json` i18n file can ping me if you have questions.
