### ISSUE TITLE
Page for Individual Campuses

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#5]
https://trello.com/c/zstKvvVH/12-page-for-individual-campuses

Hooking the mentors part up to the backend requires some backend changes. For now, just make this layout. https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=967%3A5685

- [ ] School section

- [ ] Mentors section

- [ ] pull data from /api/v1/mentor

**Comment by douglaschan32167** [comment]
I think we're going to have to assume this is in the MVP too because campus director cards is in the MVP and this is the only page on which that shows up.
https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=967%3A5685

**Comment by douglaschan32167** [comment]
Yay we get to remove this from the MVP!
