### ISSUE TITLE
Scope our migrating images to S3

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#7]
Migrate images to S3. 
Preferably, they should be keyed off a unique id on the data object, such as `mentor.id` and have canonical paths
```
def mentorImage(mentorId: String):
	s3.get("s3<mentor_base_path>://" + mentorId + ".jpg")
```

- [ ] Scope out

**Comment by jessewoo** [comment]
@ktham - wondering if you can take over on this task?  

I think @richyen is pretty busy with leading mission team and he's a father of 3 :)

**Comment by ktham** [comment]
Hi @jessewoo , I can't see the trello card, but yes, I will set up S3 and can work with the frontend folks and ensure they can access S3 so they can upload whatever they need to upload

**Comment by ktham** [comment]
After all that is set up, later, I'll set up Cloudfront

**Comment by JonSEng** [comment]
Hi I've repurposed this issue to migrate our images into S3. Some more investigation to be done to figure out how that'll work. I can type up instructions as we go.
One consideration is that it'll break local dev if we point to S3 on local as well and that doesn't have any images.
