### ISSUE TITLE
Blog Landing Page API Backend

### ISSUE THREAD

**Issue by kailanjian** [International-Mentorship-ISMP/ismp#70]
- Endpoint to Get List of Topics
  - Don't worry aboout pagination/number for now
- Featured -> just use existing
- Endpoint to provide topic and get list of blogposts

**Comment by douglaschan32167** [comment]
I think these are all done.
/api/v1/topic
/api/v1/blogpostcontent/?featured=true
/api/v1/topic should do this now. You can also /api/v1/blogpostcontent/?topic=

**Comment by kailanjian** [comment]
Yup you're right this is not really necessary, I started working on it but didn't realize they were all done
