### ISSUE TITLE
Populate non-sensitive fixtures in preparation for website launch

### ISSUE THREAD

**Issue by douglaschan32167** [International-Mentorship-ISMP/ismp#79]
Non-sensitive information will be loaded into the website by using fixtures. We need to start filling out the fixtures with the information that we want.

- [ ]  Populate schools with the list of schools that we want to highlight
- [x] Populate topics with descriptions. There will only be 4 and they can be found here https://3.basecamp.com/4474129/buckets/16925967/documents/2735700785#__recording_2742830011

**Comment by JonSEng** [comment]
Hi @douglaschan32167 

>  Populate schools with the list of schools that we want to highlight

Where do I get this list of schools that we want to highlight?
And do they go here in [`school.json`](https://github.com/International-Mentorship-ISMP/ismp/blob/master/backend/api/school/fixtures/school.json)?

**Comment by JonSEng** [comment]
cc @lillyglin bump

**Comment by lillyglin** [comment]
@JonSEng @douglaschan32167 Added some thoughts on BC. Not thoroughly fleshed out--but let's continue the conversation.
