### ISSUE TITLE
Add in scaffolding for all mentors to be listed

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#9]
Build out the mentors page to read from static front-end assets. This should be responsive and work across browsers.

## Mentor Slots
Checked off if there is a spot for them on the mentors page. Many are still missing photos and proper descriptions. That can be done by other teams.

| Your campus                      | Featured Mentor Name  |
| -------------------------------- | --------------------- |
| Diablo Valley College            | Jenny Young           |
| Diablo Valley College            | Larry Tung            |
| George Mason University          | May Huang             |
| George Mason University          | Philip Chen           |
| George Mason University          | Wongwaree "Arie" Chen |
| George Mason University          | Xin Huang             |
| Orange Coast College             | David Tung            |
| Orange Coast College             | Eileen Salvador       |
| Orange Coast College             | Sharon Tung           |
| Rutgers                          | Matthew Sallady       |
| Sac State                        | Angel Fong            |
| Sac State                        | Gary Chang            |
| The George Washington Univeristy | Maggie Hacker         |
| U of Minnesota                   | Esther Zhu            |
| U of Minnesota                   | Ian Beh               |
| U of Minnesota                   | Jon Fu                |
| UC Berkeley                      | Daniel Liu            |
| UC Berkeley                      | Marissa Brooks        |
| UC Berkeley                      | Mimi Chen             |
| UC Berkeley                      | Nancy Huang           |
| UC Davis                         | Conrad Chu            |
| UC Davis                         | Lee Yang              |
| UC Davis                         | Madelyn Lam           |
| UC Davis                         | Sandra Lee            |
| UCI                              | Jonathan Eng          |
| UCI                              | Larry Tan             |
| UCI                              | Raymond Yan           |
| UCI                              | Stacy Song            |
| UCLA                             | Alex Lee              |
| UCLA                             | Andrew Chen           |
| UCLA                             | Angela Chen           |
| UCSD                             | Douglas Chan          |
| UCSD                             | Micaela Trujillo      |
| UCSD                             | Ryan Lathan           |
| UNC Chapel Hill                  | Connie Xiong          |
| UNC Chapel Hill                  | Justin Yu             |
| UNC Chapel Hill                  | Linda Yu              |
| University of Maryland           | Angela Kim            |
| University of Maryland           | David Kim             |
| USC                              | Irene Thomas          |
| USC                              | Jerome Gonzaga        |
| USC                              | Joel Letro            |
| UT Austin                        | Annie Glass           |
| UT Austin                        | Henry Chen            |
| UT Austin                        | Stephanie Lei         |
| UT Austin                        | Wesker Lei            |
| UW                               | Ana Zhong             |
| UW                               | Howard Noz            |
| UW                               | Kevin Limkrailassiri  |

**Comment by douglaschan32167** [comment]
Couple notes on scope: For now, since we're not doing the campus-specific mentor page until v2, don't bother making the campus name a link. Also, we may not need the search dropdown so deprioritize that.

**Comment by JonSEng** [comment]
Hi Lillian cc @douglaschan32167 and @richyen I've locked down the requirements from the [sheet](https://trello.com/c/NfPS7L1e/36-mentors-page) by copying it into the [markdown table here](https://github.com/International-Mentorship-ISMP/ismp/issues/9#issue-632751220). Hopefully this won't change as we work on it 😄

**Comment by richyen** [comment]
Can you buy a chisel and put it in stone too??? 🤣

**Comment by JonSEng** [comment]
Hi @douglaschan32167 and @richyen could you help me flesh out what the goal of this ticket is a bit more?
From what I see:
1. [`MentorCards.jsx`](https://github.com/International-Mentorship-ISMP/ismp/blob/master/frontend/src/components/MentorCards/MentorCards.jsx) hard codes the mentor info on the front-end right now.
1. We already have backend end points ready for retrieving mentors (e.g. `ListMentorView`)

What I'm guessing we are hoping to do within V1 scope is:
1. Get the front-end to read from the back-end's returned data instead of `MentorCards.jsx`
1. Add a `campus` field (unlinked). This will be part of the backend fixture.

Open Questions:
1. What's our approach for serving images to the front-end, specifically here for the mentor photos? Where are/should they be stored?
1. When and where will we get these photos and finalized descriptions for the mentors?
1. Would @douglaschan32167 @richyen let me know what I'm missing?

Thanks!

**Comment by lillyglin** [comment]
@douglaschan32167 @JonSEng 

WellLLlllLLll, Douglas has already checked re: the mentor page and clarified scope. BUT because we aren't doing separate campus pages, v1 should organize the page with the grid cards broken up by a H2 tag for campus name.

**Comment by JonSEng** [comment]
> I was also under assumption of fixed front-end assets, esp. we're limiting to about 20 mentors.

Okay if that's the case then it seems this ticket is blocked on the descriptions and photos.
Sure the formatting and text can be tweaked but it'd look similar to what we have now:
[http://localhost:3000/mentors](http://localhost:3000/mentors)
<img width="1279" alt="Screenshot 2020-06-09 23 00 51" src="https://user-images.githubusercontent.com/1644269/84232428-1cef6c00-aaa5-11ea-93c1-78b36f2cf9a0.png">

**Comment by lillyglin** [comment]
@JonSEng @douglaschan32167 Yeah pretty much. I'll let you guys know when I get assets.

**Comment by JonSEng** [comment]
> @JonSEng @douglaschan32167 Yeah pretty much. I'll let you guys know when I get assets.

Marked as blocked until then.
In the meantime, I can take a poke and see if there are other loose ends we'd like to address for this.

**Comment by JonSEng** [comment]
Removing "backend" label since this is scoped only for FE.

**Comment by lillyglin** [comment]
@albertjke I've updated with a few more details.

**Comment by douglaschan32167** [comment]
Hey guys,
The doc where the survey results are is here https://docs.google.com/spreadsheets/d/1bjwcQv3gHALI_ZM2M7Rog_GknU_cxC41kPCfO14AFsM/edit#gid=752511424

You can see which mentors will be displayed for which campuses and there's a link to a dropbox with some pictures.

**Comment by jessewoo** [comment]
![image](https://user-images.githubusercontent.com/12104578/85100549-3f743a00-b1b5-11ea-9767-998c831736e9.png)
this card looks more clean

**Comment by JonSEng** [comment]
Blocked on assets - [Basecamp todo](https://3.basecamp.com/4474129/buckets/16925967/todos/2770510087#__recording_2774316940)
